/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	learn: [
		"learn/overview",
		{
			Tutorial: [
				"learn/tutorial/introduction",
				"learn/tutorial/fluree-data-model",
				"learn/tutorial/working-with-graph-data",
				"learn/tutorial/collaborative-data",
			],
		},
		{
			Guides: [
				"learn/guides/working-with-context",
				"learn/guides/working-with-ontologies",
			],
		},
		{
			Foundations: [
				"learn/foundations/json-ld",
				"learn/foundations/querying",
				"learn/foundations/data-access-control",
				"learn/foundations/verifiable-data",
				"learn/foundations/semantic-vocabularies",
				"learn/foundations/architecture-overview",
				"learn/foundations/from-tables-to-graphs",
			],
		},
	],
	examples: [
		{
			"Sharing Secure, Trusted Data": [
				"examples/datasets/academic-credentials/introduction",
				"examples/datasets/academic-credentials/querying",
			],
		},
	],
	reference: [
		"reference/http-api",
		"reference/cloud-http-api",
		"reference/fluree-server-config",
		"reference/flureeql-query-syntax",
		"reference/history-syntax",
		"reference/transaction-syntax",
		"reference/cookbook",
		"reference/error-codes",
		"reference/policy-syntax",
		"reference/data-types",
	],
	cloud: [
		"cloud/welcome",
		{
			type: "category",
			label: "Getting Started",
			items: [{ type: "autogenerated", dirName: "cloud/getting-started" }],
		},
		{
			type: "category",
			label: "Dataset View",
			items: [
				"cloud/datasets/overview",
				"cloud/datasets/about",
				"cloud/datasets/settings",
				"cloud/datasets/notebooks",
				"cloud/datasets/policies",
				"cloud/datasets/view-data",
				// {
				// 	type: "category",
				// 	label: "Data Management",
				// 	items: [
				// 		{
				// 			type: "autogenerated",
				// 			dirName: "cloud/datasets/data-management",
				// 		},
				// 	],
				// },
				// { type: "autogenerated", dirName: "cloud/datasets/dataset-pages" },
			],
		},
		{
			type: "category",
			label: "How-To Guides",
			items: [
				"cloud/how-to/connect-apps",
				// "cloud/how-to/apply-policy",
				{
					type: "category",
					label: "Fluree + GenAI",
					items: [
						{
							type: "doc",
							id: "cloud/how-to/chat/quickstart",
							label: "Quickstart Guide",
						},
						{
							type: "category",
							label: "Data Agent",
							items: [
								{
									type: "doc",
									id: "cloud/how-to/chat/intro",
									label: "Introduction",
								},
								{
									type: "doc",
									id: "cloud/how-to/chat/with-unstructured",
									label: "Chat with Documents",
								},
								{
									type: "doc",
									id: "cloud/how-to/chat/with-structured",
									label: "Chat with Tables",
								},
								{
									type: "doc",
									id: "cloud/how-to/chat/local-mcp-server",
									label: "LLM Client Integration (MCP)",
								},
								// {
								// 	type: "doc",
								// 	id: "cloud/how-to/chat/with-ontology",
								// 	label: "Chat with Graph Data",
								// },
							],
						},
					],
				},
			],
		},
	],
  senseSidebar: [{ type: 'autogenerated', dirName: 'sense' }],
};

